### ISSUE TITLE
structural directive 파트에서 asterisk 문법을 사용하세요 부분 오탈자 수정

### ISSUE THREAD

**Issue by ghost** [han41858/angular-ko#23]
[별표(*) 문법을 사용하세요.](https://angular.kr/guide/structural-directives#%EB%B3%84%ED%91%9C-%EB%AC%B8%EB%B2%95%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%84%B8%EC%9A%94) 부분을 읽어보다가 조금 다른 말인 것 같아서ㅎㅎ;

> 그래서 템플릿의 어트리뷰트 나 엘리먼트 폼 에 구조 디렉티브를 적용하려면 `<ng-template>`을 어떻게 활용하면 좋을지 고민해보는 것도 좋습니다. `<ng-template>`은 커스텀 구조 디렉티브를 정의할 때도 활용됩니다.

> While there's rarely a good reason to apply a structural directive in template attribute or element form, it's still important to know that Angular creates a `<ng-template>` and to understand how it works. You'll refer to the `<ng-template>` when you write your own structural directive.

원문은 "asterisk 문법을 놔두고 structural directive를 desugared된 형태로 **template attribute**(`NgIf` 디렉티브의 경우 `ngIf` template attribute) 또는 **template element**(이 경우는 추측 상 `<ng-template>` element?) 형식으로 사용할 이유는 딱히 없지만, 그렇다 하더라도 ~~"의 의미인 것 같아서요. '폼'이라는 말이 `NgForm`을 떠올리는 것 같아서 조금 혼란이 있을 수 있지 않을까요?

[구조 디렉티브란?](https://angular.kr/guide/structural-directives#%EA%B5%AC%EC%A1%B0-%EB%94%94%EB%A0%89%ED%8B%B0%EB%B8%8C%EB%9E%80) 파트의 '디렉티브의 대소문자 구분' 부분에 보니 `"NgIf는 디렉티브 클래스 자체를 가리키며, ngIf는 디렉티브를 적용할 때 사용하는 어트리뷰트 이름 을 가리킵니다."`라고 되어 있어서 **template attribute**는 `NgIf`의 `ngIf`를 말하는 건 맞는 것 같은데, **template element**라는 말이 `<ng-template>`을 말하는 것인지는 확실하지는 않습니다:

```html
<!-- asterisk 문법 -->

<div *ngIf="condition">Content to render when condition is true.</div>
```

```html
<!-- desugared -->

<ng-template [ngIf]="condition">
    <div>Content to render when condition is true.</div>
</ng-template>
```

마지막으로, 방대한 문서를 번역해주셔서 감사합니다ㅎㅎ 덕분에 편하게 볼 수 있을 것 같아요.

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 부분을 다시 읽어보니 이상하네요 ㅎㅎㅎ;;
원문의 순서도 좀 이상한 것 같아서 이렇게 수정했습니다.

* 원문
> The asterisk (*) syntax is more clear than the desugared form.
> Use [&lt;ng-container&gt;] when there's no single element
to host the directive.
> 
> While there's rarely a good reason to apply a structural directive in template _attribute_ or _element_ form,
> it's still important to know that Angular creates a `<ng-template>` and to understand how it works.
> You'll refer to the `<ng-template>` when you [write your own structural directive].

* 수정 전
> `<ng-template>`으로 변환된 HTML 구조보다는 별표(`*`)를 사용한 문법이 좀 더 간결합니다.
> 
> 그래서 템플릿의 _어트리뷰트_ 나 _엘리먼트 폼_ 에 구조 디렉티브를 적용하려면 `<ng-template>`을 어떻게 활용하면 좋을지 고민해보는 것도 좋습니다. `<ng-template>`은 [커스텀 구조 디렉티브]를 정의할 때도 활용됩니다.

* 수정 후
> `<ng-template>`을 직접 사용하는 것보다는 별표(`*`)를 사용한 문법이 좀 더 간결합니다.
> 그리고 별표(`*`) 문법을 사용하지 않고 _어트리뷰트_ 형태나 `<ng-template>` 형태로 구조 디렉티브를 사용했을 때 더 나은 점도 딱히 없습니다.
> 그래서 구조 디렉티브는 별표(`*`)를 붙여 축약된 문법으로 사용하는 것을 권장합니다.
>
> 별표(`*`) 문법이 사용된 엘리먼트는 Angular가 `<ng-template>`으로 변환한다는 것을 알고 넘어가는 것이 중요합니다.
> `<ng-template>`은 [커스텀 구조 디렉티브]를 정의할 때도 활용됩니다.
>
> 디렉티브가 조작하는 엘리먼트가 여러개라면 [&lt;ng-container&gt;]를 사용하는 것도 좋습니다.

해당 문서 쭉 읽어보면서 좀 더 읽기 편하도록 수정했습니다.

감사합니다!! ^^
