### ISSUE TITLE
튜토리얼 시작하기의 3번째 줄 오탈자 수정

### ISSUE THREAD

**Issue by Park-Jongseok** [han41858/angular-ko#24]
- 주소 : https://angular.kr/guide/quickstart

- 문제점

> 두가지는 이 문서 뿐 아니라 모든 Angular 프로젝에 적용하는 것을 권장합니다.

- 수정안

> 두가지는 이 문서 뿐 아니라 모든 Angular 프로젝트에 적용하는 것을 권장합니다.

별거 아니지만ㅠㅠ 완벽하면 보기 좋을것 같아서요!

튜토리얼 잘보고 있습니다. 감사합니다.

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

확인했습니다. 곧 수정하겠습니다!! ㅎ

감사합니다.

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정해서 angular.kr에 반영했습니다.
https://angular.kr/guide/quickstart#시작하기

감사합니다^^
