### ISSUE TITLE
Angular 튜토리얼 - 5. 라우팅 

### ISSUE THREAD

**Issue by Park-Jongseok** [han41858/angular-ko#26]
- 주소 :
https://angular.kr/tutorial/toh-pt5

- 문제점
5. 라우팅 - AppRoutingModule 생성하기 - src/app/app-routing.module.ts (Angular CLI가 생성한 라우팅 모듈)아래의 설명 3번째 줄
 @NgModule.expors

- 수정안
 @NgModule.exports

**Comment by Park-Jongseok** [comment]
exports라고 생각하는데, t가 빠진것 같습니다!

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정해서 angular.kr에 반영했습니다.
https://angular.kr/tutorial/toh-pt5

감사합니다^^
