### ISSUE TITLE
Angular 튜토리얼 - 6. HTTP

### ISSUE THREAD

**Issue by Park-Jongseok** [han41858/angular-ko#27]
- 주소 : 
https://angular.kr/tutorial/toh-pt6#%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%84%9C%EB%B2%84-%EB%AA%A9%ED%82%B9%ED%95%98%EA%B8%B0

- 문제점
데이터 서버 목킹하기 항목의 
The forRoot() configuration method takes an InMemoryDataService class that primes the in-memory database.
The class src/app/in-memory-data.service.ts is generated by the following command:
content_copy
ng generate service InMemoryData 
This class has the following content:
의 번역과
src/app/in-memory-data.service.ts의 소스코드가 누락되어있습니다.

- 수정안
해당 부분이 전체 주석 처리 되어있어서 화면에 출력 되지 않습니다.

**Comment by PARK-JONGSEOK** [comment]
- 주소 : 
https://angular.kr/tutorial/toh-pt6#httpclient-%EB%A1%9C-%ED%9E%88%EC%96%B4%EB%A1%9C-%EB%AA%A9%EB%A1%9D-%EA%B0%80%EC%A0%B8%EC%98%A4%EA%B8%B0

- 문제점:
/** GET: 서버에서 히어로 목록 가져오기 */
getHeroes (): Observable<Hero[]> {
  return this.http.get<Hero[]>(this.heroesUrl)
}
세미콜론이 없습니다. (영문 홈페이지에도 없어요!)
없어도 괜찮나요? 잘 몰라서 질문드립니다.

- 수정안:
/** GET: 서버에서 히어로 목록 가져오기 */
getHeroes (): Observable<Hero[]> {
  return this.http.get<Hero[]>(this.heroesUrl);<<<
}

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정해서 angular.kr에 반영했습니다.
https://angular.kr/tutorial/toh-pt6#데이터-서버-목킹하기

감사합니다^^
