### ISSUE TITLE
Angular 기초지식 - 아키텍처 개요

### ISSUE THREAD

**Issue by Park-Jongseok** [han41858/angular-ko#28]
- 주소 :
https://angular.kr/guide/architecture#%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-%EA%B0%9C%EC%9A%94
위에서 8번째 줄입니다!
- 문제점
컴폰너트

- 수정안
컴포넌트

**Comment by PARK-JONGSEOK** [comment]
- 주소 :
https://angular.kr/guide/architecture#%EB%AA%A8%EB%93%88
첫번째 줄입니다!

- 문제점
컴포넌

- 수정안
컴포넌트

**Comment by Park-Jongseok** [comment]
- 주소 :
https://angular.kr/guide/architecture#%EB%AA%A8%EB%93%88
첫번째 줄입니다!

- 문제점
컴포넌

- 수정안
컴포넌트

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당내용 수정되어 angular.kr에 반영되었습니다.
https://angular.kr/guide/architecture#아키텍처-개요

도움주셔서 정말 고맙습니다!
