### ISSUE TITLE
기초지식 - 컴포넌트 & 템플릿 - 구조 디렉티브

### ISSUE THREAD

**Issue by Park-Jongseok** [han41858/angular-ko#29]
- 주소 : https://angular.kr/guide/structural-directives#%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95--ng-container

- 문제점
해결방법 : `<ng-container>`의 첫 번째 줄입니다!
유지함녀서

- 수정안
유지하면서

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 문구 오류 수정했습니다. 감사합니다^^
