### ISSUE TITLE
환경설정 & 배포 - 워크스페이스 설정

### ISSUE THREAD

**Issue by Park-Jongseok** [han41858/angular-ko#30]
- 주소 : 
  - https://angular.kr/guide/workspace-config#json-%EC%B5%9C%EC%83%81%EC%9C%84-%EA%B3%84%EC%B8%B5

- 문제점
  - JSON json-최상위-계층의 8번째 줄
  -  이 앱은 "projects" 목록에 둥록되는데, 

- 수정안
 -  이 앱은 "projects" 목록에 등록되는데,

**Comment by Park-Jongseok** [comment]
https://github.com/han41858/angular-ko/issues/28#issuecomment-484767956

고생하십니다. 지난번 이슈에서 하나가 빠진것 같습니다ㅠㅠ 모듈의 첫번째 줄입니다.

덕분에 잘보고 있습니다 ! 감사합니다.

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당내용 수정되었습니다~

매번 고맙습니다^^
