### ISSUE TITLE
기초지식 - 폼 - 반응형 폼 

### ISSUE THREAD

**Issue by Park-Jongseok** [han41858/angular-ko#31]
- 주소 :
  - https://angular.kr/guide/reactive-forms#%ED%8F%BC-%EC%BB%A8%ED%8A%B8%EB%A1%A4-%EA%B0%92-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0

- 문제점
3번째 줄입니다.
밸엔드

- 수정안
백엔드

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정되어 레파지토리에 반영되었습니다.
웹페이지에는 다음 배포때 반영될 예정입니다.

매번 고맙습니다^^
