### ISSUE TITLE
기초지식 - 컴포넌트 & 템플릿 - 파이프

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#32]
- 주소 : https://angular.kr/guide/pipes#%ED%8C%8C%EC%9D%B4%ED%94%84-%EC%9D%B8%EC%9E%90-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

- 문제점
예제의 소스코드 중 주석 부분에 오타가 있어 보입니다.

  - src/app/hero-birthday2.component.ts (class) - 세번째 예제
`  toggle = true; // 기본 형식을 shortDate로 지정하기 위해 ture 값을 할당합니다.`
ture

- 수정안
true

좋은 자료 번역해주셔서 너무 감사드립니다. 항상 잘 참고하고 있습니다. :smile:

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정되어 가이드문서에 반영되었습니다.

도움을 주셔서 고맙습니다^^
