### ISSUE TITLE
기초지식 - 컴포넌트 & 템플릿 - 파이프

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#33]
- 주소 : https://angular.kr/guide/pipes#pipetransform-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4

- 문제점

> DECLARATIONS 배열에 꼭 등록하세요.
...  Angular CLI's를 사용해서 파이프를 생성하면, 이 파이프는 AppModule에 자동으로 등록됩니다.

Angular CLI's

한국어 번역이기 때문에 Angular CLI가 맞지 않나 생각되어 이슈 남깁니다.

- 수정안
Angular CLI

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정되어 가이드문서에 반영되었습니다.

도움을 주셔서 고맙습니다^^
