### ISSUE TITLE
튜토리얼 - 라우팅

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#34]
- 주소 : https://angular.kr/tutorial/toh-pt5#%EB%9D%BC%EC%9A%B0%ED%8C%85-%EB%B3%80%EC%88%98-id-%EC%B6%94%EC%B6%95%ED%95%98%EA%B8%B0

- 문제점
라우팅 변수 id 추축하기

- 수정안
라우팅 변수 id 추출하기

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정되어 [가이드 문서](https://angular.kr/tutorial/toh-pt5#라우팅-변수-id-추출하기)에 반영되었습니다.


도움주셔서 감사합니다 ^^
