### ISSUE TITLE
기초지식 - 컴포넌트 & 템플릿 - 어트리뷰트 디렉티브

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#38]
- 주소 : https://angular.kr/guide/attribute-directives#%EB%B6%80%EB%A1%9D-%EC%99%9C-input-%EA%B0%80-%ED%95%84%EC%9A%94%ED%95%A0%EA%B9%8C

- 문제점
입력 프로퍼티에 별칭을 지정하지 않는 경우라몀ㄴ 다음과 같이 사용했습니다:

- 수정안
입력 프로퍼티에 별칭을 지정하지 않는 경우라면 다음과 같이 사용했습니다:

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정되어 [가이드 문서](https://angular.kr/guide/attribute-directives#부록-왜-input-가-필요할까)에 반영되었습니다.

도움주셔서 감사합니다 ^^
