### ISSUE TITLE
기초지식 - 라우팅 & 네비게이션 - 히어로 모듈 라우팅

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#39]
- 주소 :https://angular.kr/guide/router#%ED%9E%88%EC%96%B4%EB%A1%9C-%EB%AA%A8%EB%93%88-%EB%9D%BC%EC%9A%B0%ED%8C%85

- 문제점
<<<<<<< HEAD

- 수정안
(제거)

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용 수정되어 [가이드 문서](https://angular.kr/guide/router#히어로-모듈-라우팅)에 반영되었습니다.

도움주셔서 감사합니다 ^^
