### ISSUE TITLE
기초지식 - HttpClient - next 객체

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#40]
- 주소 : https://angular.kr/guide/http#next-%EA%B0%9D%EC%B2%B4

- 문제점
next 객체는 체이팅되는

- 수정안
next 객체는 체이닝되는

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용은 수정되어 [가이드문서](https://angular.kr/guide/http#next-객체)에 반영되었습니다.

도움주셔서 고맙습니다^^
