### ISSUE TITLE
기초지식 - 폼 - 반응형 폼

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#41]
- 주소 : https://angular.kr/guide/reactive-forms#2단계---formarray-정의하기

- 문제점
중복된 내용
```
FormArray는 배열로 초기화하며, 이 때 배열의 길이는 어떠한 것이라도 가능합니다. profileForm에 aliases 프로퍼티를 추가하고, 이 프로퍼티를 FormArray로 정의해 봅시다.

폼 배열은 배열로 초기화하며, 이 때 배열의 길이는 어떠한 것이라도 가능합니다. profileForm에 aliases 프로퍼티를 추가하고, 이 프로퍼티를 폼 배열로 정의해 봅시다.
```

- 수정안
중복 삭제 필요

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용은 angular.io 문서가 업데이트되면서 두번째 문장으로 변경된 것으로 확인했습니다.
말씀하신대로 중복된 내용이니 첫번째 문장을 제거하는 것이 맞습니다.

해당 내용 처리되어 [문서](https://angular.kr/guide/reactive-forms#2단계---formarray-정의하기)에 반영되었습니다.

도움주셔서 고맙습니다^^
