### ISSUE TITLE
로컬 개발환경, 워크스페이스 구성하기 - 오탈자 수정

### ISSUE THREAD

**Issue by yeonfeel** [han41858/angular-ko#43]
- 주소 : https://angular.kr/guide/setup-local

- 문제점
npm 패키지 매니저 단락에 아래 문장에서
> Angular와 Angular CLI, Angular로 동작하는 **애배**은 모두 npm 패키지 형태로 제공되는 라이브러리를 사용해서 동작합니다.

단어 "애배"

- 수정안
적절한 단어로 수정 예) 예제는

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용은 제안해주신 내용으로 수정되어 angular.kr 해당 문서에 반영되었습니다.

도움주셔서 고맙습니다^^
