### ISSUE TITLE
로컬 개발환경, 워크스페이스 구성하기 - 오탈자 수정2

### ISSUE THREAD

**Issue by yeonfeel** [han41858/angular-ko#44]
- 주소 : https://angular.kr/guide/setup-local

- 문제점
3단계: 애플리케이션 실행하기 단락에 아래 문장

> 워크프레이스 폴더로 이동합니다. (이 경우에는 my-app)

단어 워크프레이스 오탈자 수정

- 수정안
적절한 단어로 수정 예) 워크스페이스

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용은 제안해주신 내용으로 수정되어 angular.kr 해당 문서에 반영되었습니다.

도움주셔서 고맙습니다^^
