### ISSUE TITLE
개발단계 - 테스트 - 코드 커버리지 강제하기

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#47]
- 주소 : https://angular.kr/guide/testing#%EC%BD%94%EB%93%9C-%EC%BB%A4%EB%B2%84%EB%A6%AC%EC%A7%80-%EA%B0%95%EC%A0%9C%ED%95%98%EA%B8%B0

- 문제점
띄어쓰기

- 수정안
코드 커버리지는8 0% 이상이 -> 코드 커버리지는 80% 이상이

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용은 제안해주신 내용으로 수정되어 angular.kr 해당 문서에 반영되었습니다.

도움주셔서 고맙습니다 :)
