### ISSUE TITLE
개발단계 - 테스트 - 컴포넌트 클래스 테스트

### ISSUE THREAD

**Issue by younghoh** [han41858/angular-ko#48]
- 주소 : https://angular.kr/guide/testing#%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%ED%81%B4%EB%9E%98%EC%8A%A4-%ED%85%8C%EC%8A%A4%ED%8A%B8

- 문제점
welcome.component.spec.ts 예제 코드 제목 부분 오타

- 수정안
app/welcome/welcome.component.spec.ts (컴포넌트 클래스 테슷트하기) -> ... (컴포넌트 클래스 테스트하기)

**Comment by han41858** [comment]
안녕하세요 한장현입니다.

해당 부분은 말씀하신 내용으로 수정되어 angular.kr에 반영되었습니다.
도움을 주셔서 고맙습니다 :)
