### ISSUE TITLE
행사정보 페이지 오류

### ISSUE THREAD

**Issue by kdongha** [han41858/angular-ko#49]
- 주소 : https://github.com/han41858/angular-ko/blob/master/aio/content/marketing/events.html

- 문제점 
conflict가 난 코드들이 그대로 노출되고 있습니다.

- 수정안 
conflict해결이 필요할 것 같습니다. 
또한 ngVikings 행사의 정보가 번역전에는 Oslo, Norway 이지만 번역 후 덴마크로 변경되었습니다.

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 문서는 머지가 잘못되어 있었네요 ㅠㅠ
angular.io 기준으로 새로 번역해서 angular.kr에 반영했습니다.

도움을 주셔서 고맙습니다 :)
