### ISSUE TITLE
파이프로 데이터 표시형식 변환하기 - 오탈자 수정

### ISSUE THREAD

**Issue by 7dayz** [han41858/angular-ko#62]
- 주소 : https://angular.kr/guide/pipes

- 문제점
"HTTP 요청 캐싱하기" 파트 내용 중
 ... 두번째 사용된 코드에는 _fetch 파이_와 기본 파이프 JsonPipe를 사용해서 데이터를 JSON 형식으로 화면에 표시합니다.

  _fetch 파이_  오탈자 수정이 필요합니다.

- 수정안
  fetch 파이프

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

오타가 있었네요ㅠ
수정해서 다음 빌드 때 반영하겠습니다.

도움 주셔서 감사합니다 :)
