### ISSUE TITLE
싱글턴 서비스 번역 오류

### ISSUE THREAD

**Issue by minnsane** [han41858/angular-ko#68]
- 주소 : https://angular.kr/guide/singleton-services

- 문제점
싱글턴 서비스 생성하기의 두번째 항목 번역 오류

- 수정안
서비스를 AppModule에 포함시키거나, AppModule에서만 로드되는 module에 포함시키는 방법

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 문장은 번역이 잘못된 것으로 확인했습니다 ㅠ

말씀해주신 내용 참고해서 바로 반영하겠습니다.

도움 주셔서 감사합니다 :)
