### ISSUE TITLE
Expr -> Expression

### ISSUE THREAD

**Issue by jamiecha** [han41858/angular-ko#69]
- 내용:
  - component class 에는 classExpression, styleExpression 으로 프로퍼티가 설정되어 있는데 템플릿에서 classExpr, styleExpr 로 바인딩 하고 있어서 빌드 에러가 발생합니다. angular.io 예제를 따랐습니다.

- 주소 :
angular-ko/aio/content/examples/attribute-binding/src/app/app.component.html

- 문제점
`<div [class.special]="isSpecial" [class]="classExpr">Some text.</div>`
`<div [style.color]="color" [style]="styleExpr">Some text.</div>`

- 수정안
`<div [class.special]="isSpecial" [class]="classExpression">Some text.</div>`
`<div [style.color]="color" [style]="styleExpression">Some text.</div>`

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 내용은 머지가 잘못된 것으로 확인했습니다 ㅠ

말씀하신 내용이 맞으니 그대로 바로 반영하겠습니다!

감사합니다 ㅎ
