### ISSUE TITLE
click.directive.ts 에 중복 라인으로 에러 발생

### ISSUE THREAD

**Issue by jamiecha** [han41858/angular-ko#70]
- 주소 : angular-ko/aio/content/examples/template-syntax/src/app/click.directive.ts

- 문제점
    - `outputs` 프로퍼티가 중복으로 기입되어 빌드 에러 발생 
```html
@Directive({
  selector: '[myClick2]',
  // tslint:disable: no-outputs-metadata-property
  outputs: ['clicks:myClick']  // propertyName:alias
  outputs: ['clicks:myClick']  // 프로퍼티_이름:별칭
})
```

- 수정안
    - 중복 라인 제거

- 감사
    - angular 공부하는데 엄청나게 큰 도움을 받고 있습니다. 
    - 의미 해석이 너무 잘 되어 있고 심지어 코드에 주석까지 달아 주셔서 원문 읽는 것에 비해 진도가 엄청 빠르네요. 
    - 감사합니다!

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

머지가 잘못되었네요.. ㅎ
말씀하신대로 수정해서 바로 반영하겠습니다~!

도움을 주셔서 감사합니다 👍 

제가 작업하는 내용이 도움이 되고 있다니 다행이네요 ㅎㅎ
